# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODcxYTkyNmI0ZDU0OWIzNzI5OTIxNDYyMmU4NDc1MGRiMGQyMzljYTdkNDNmNzU2MWQ3NDk4M2I4YjEzZDFjZjc3YmExZDlmOWIzNTkyMWU5YWNlMzg4YjVmZmI5ZWYwOGNiYjVjZTU2ZGNhYmQ1OGJiMThhMTU3OTlkNjQ4YWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
